Add Error Handle
nick6969/Refactor-Talk pull request #2
Opened 2020-10-05 08:37 UTC by nick6969

# Error Handle

一個 api call 過程當中會有許多 Error
但是外部不必要全部都要知道
所以定義一個 LoaderError，讓外部可以根據幾個特定狀態處理
而不用猜測 Error 的來源

2020-10-06 07:03 UTC, ytyubox commented
@dsxsxsxs 我在思考一件事情，上次對於 `loadData`的要求因為在PR內，容易導致PR肥大，我提議要求在討論完後，使用 issue 來發布

2020-10-06 07:05 UTC, nick6969 commented
同意，一般的運作模式就是提出問題，若問題超出這一個 PR 的範圍，另外開 issue.

2020-10-06 07:05 UTC, ytyubox requested changes
我有 1 個疑問、1 個建議修改、2 個討論要求，請幫忙確認，謝謝

2020-10-06 07:05 UTC, the-yuyut commented on talk/SessionLoader.swift
> +        failure: ((LoaderError) -> Void)?
success 與 failure 是 `Optional` 的原因可以解釋一下嗎？

2020-10-06 07:05 UTC, the-yuyut commented on talk/SessionLoader.swift
> +            }
```suggestion
            if let err = err {
                failure?(.urlSessionError(err))
                return
            }
```
使用 Swift 語言的 `if let` 語法簡化不必要的 `err!`，可以提升閱讀性

2020-10-06 07:05 UTC, the-yuyut commented on talk/SessionLoader.swift
> +}
我覺得這個部分可以考慮在其他 pr 討論，不過看起來是新手常用的方式，可以先 merge

2020-10-06 07:05 UTC, ytyubox commented on talk/MainVC.swift
> +        let successHandle: (AreaContentModel) -> Void = { success?($0.data) }
這段程式碼在 3 個地方重複了，分別是 `MainVC.loadData(success:)`, `LineVC.loadData(success:)`, `LineDetailVC.loadData(success:)`，感覺可以在其他PR 討論

2020-10-06 07:19 UTC, nick6969 commented on talk/SessionLoader.swift
> +            }
都可
這兩個寫法在我個人閱讀而言 是等意的

2020-10-06 07:21 UTC, nick6969 commented on talk/MainVC.swift
> +        let successHandle: (AreaContentModel) -> Void = { success?($0.data) }
這裡個人覺得不是重複，因為這是不同 api 回應的不同 model，只是剛好都是 data 欄位(server api 有固定規格)
但可以在後續優化 network layer 時再討論

2020-10-06 07:34 UTC, nick6969 commented on talk/SessionLoader.swift
> +        failure: ((LoaderError) -> Void)?
習慣性使然
我以前都是先實作好 success closure 跟 failure closure 放在 store property，直接傳遞給網路層，所以會用 optional 來避免 Memory leak

ex: 
 - https://github.com/nick6969/CHL_MVP/blob/master/CHLMVP/Classes/BasePresenter.swift
 - https://github.com/nick6969/CHL_MVP/blob/master/Example/CHLMVP/ShowDataPresenter.swift

2020-10-06 07:58 UTC, ytyubox commented on talk/SessionLoader.swift
> +        failure: ((LoaderError) -> Void)?
但是在目前的需求，提供 `nil` 與 ` {_ in}` 是同樣的道理，可以考慮看看閱讀性，參數使用哪一個比較合理。
或許可以等看看其他人意見，或是在社團主動投票？

2020-10-06 11:14 UTC, dsxsxsxs commented on talk/SessionLoader.swift
> +        failure: ((LoaderError) -> Void)?
沒啥苦衷的話我也是直接定義成 escaping closure居多就是

2020-10-06 11:14 UTC, dsxsxsxs commented on talk/SessionLoader.swift
> +                failure?(.noData)
[nits]
比如說http 204的話，那就真的要空值（有值反而是錯的），新手向的話不用寫得這麼細就是，nits就好

2020-10-06 11:14 UTC, dsxsxsxs commented on talk/BaseTableVC.swift
> +            }
failure UX可以一律統一起來，實務上很少吧，我覺得ＶＣ們各自實裝就好

2020-10-06 11:17 UTC, dsxsxsxs commented on talk/BaseTableVC.swift
> +            }
或者把這個當作default行為，開出來讓子類別override之類的

2020-10-07 03:21 UTC, ytyubox approved these changes

2020-10-07 03:29 UTC, ytyubox commented on talk/SessionLoader.swift
> +                failure?(.noData)
@dsxsxsxs  可以解釋 `nits` 是什麼意思嗎？

2020-10-07 03:30 UTC, ytyubox commented on talk/BaseTableVC.swift
> +            }
event hook 好像也不錯

2020-10-07 03:33 UTC, nick6969 commented on talk/BaseTableVC.swift
> +            }
實務上，我前兩家公司跟現在這家公司，都是用同一個，只是type 不同而已
但同意可以另外開 func，當成 default implement.

2020-10-07 08:40 UTC, dsxsxsxs commented on talk/SessionLoader.swift
> +                failure?(.noData)
`nitpick`

我習慣用複數形就是，硬要加個sㄎ

2020-10-08 02:14 UTC, dsxsxsxs approved these changes

2020-10-17 04:16 UTC, merged